# Excalipoor v0.0.2
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2013

excalipoor:
  amount: 10
  item: DIAMOND_SWORD
  enchants:
    DAMAGE_ALL: 5
    FIRE_ASPECT: 5
    LOOT_BONUS_MOBS: 5
  remain: 1

crosspow:
  amount: 5
  item: BOW
  enchants:
    ARROW_KNOCKBACK: 10
    ARROW_DAMAGE: 2
  remain: 1

# -- MEMO --
# All of Enchantment types.
#   PROTECTION_ENVIRONMENTAL
#   PROTECTION_FIRE
#   PROTECTION_FALL
#   PROTECTION_EXPLOSIONS
#   PROTECTION_PROJECTILE
#   OXYGEN
#   WATER_WORKER
#   THORNS
#   DAMAGE_ALL
#   DAMAGE_UNDEAD
#   DAMAGE_ARTHROPODS
#   KNOCKBACK
#   FIRE_ASPECT
#   LOOT_BONUS_MOBS
#   DIG_SPEED
#   SILK_TOUCH
#   DURABILITY
#   LOOT_BONUS_BLOCKS
#   ARROW_DAMAGE
#   ARROW_KNOCKBACK
#   ARROW_FIRE
#   ARROW_INFINITE 
